export { default as LogoWhiteSignIn } from './logo-white-sign-in.svg';
export { default as SignInGrid } from './sign-in-grid.svg';
export { default as SignInBars } from './sign-in-bars.svg';
export { default as HomeIcon } from './home-icon.svg';
export { default as MegaPhone } from './mega-phone.svg';
export { default as BillingIcon } from './billing.svg';
export { default as BackgroundWaves } from './background-waves.svg';
export { default as ArrowIcon } from './arrow.svg'
export { default as ElocalLogo } from './elocal-logo.svg'
export { default as ArrowLeftIcon } from './arrow-left.svg'