export const Screens = {
  // AUTH_STACK
  LOGIN_SCREEN: "LOGIN_SCREEN",
  OTP_SCREEN: "OTP_SCREEN",
  FORGOT_PASSWORD_SCREEN: "FORGOT_PASSWORD_SCREEN",
  NEW_PASSWORD_SCREEN: "NEW_PASSWORD_SCREEN",

  // OTP ->  password renewal screen

  // HOME_STACK
  SWITCH_ACCOUNT_SCREEN: "SWITCH_ACCOUNT_SCREEN",
  CONTACT_SCREEN: "CONTACT_SCREEN",

  // -- SUMMARY_STACK tofix
  SUMMARY_SCREEN: "SUMMARY_SCREEN",
  SUMMERY_LEAD_DETAILS_SCREEN: "LEAD_DETAILS_SCREEN",
  SUMMERY_CALL_DETAILS_SCREEN: "CALL_DETAILS_SCREEN",

  // TODO

  // -- CAMPAIGNS_STACK  tofix
  CAMPAIGNS_SCREEN: "CAMPAIGNS_SCREEN",
  CAMPAIGN_DETAILS_SCREEN: "CAMPAIGN_DETAILS_SCREEN",
  CAMPAIGN_LISTING_SCREEN: "CAMPAIGN_LISTING_SCREEN",
  CAMPAIGN_LISTING_DETAILS_SCREEN: "CAMPAIGN_LISTING_DETAILS_SCREEN",
  EDIT_LOCATION_DETAILS_SCREEN: "EDIT_LOCATION_SCREEN",
  REMAINING_BUDGET_SCREEN: "REMAINING_BUDGET_SCREEN",

  // -- BILLING_STACK
  BILLING_SCREEN: "BILLING_SCREEN",
  PAYMENT_METHODS_SCREEN: "PAYMENT_METHODS_SCREEN",
  ADD_PAYMENT_METHOD_SCREEN: "ADD_PAYMENT_METHOD_SCREEN",

  // -- ACCOUNT_STACK
  ACCOUNT_SCREEN: "ACCOUNT_SCREEN",
  ACCOUNT_CONTACTS_SCREEN: "ACCOUNT_CONTACTS_SCREEN",
  ACCOUNT_NEW_CONTACTS_SCREEN: "ACCOUNT_NEW_CONTACTS_SCREEN",
  ACCOUNT_LOCATIONS_SCREEN: "ACCOUNT_LOCATIONS_SCREEN",
  ACCOUNT_HOLIDAYS_SCREEN: "ACCOUNT_HOLIDAYS_SCREEN",
  ACCOUNT_PAUSES_SCREEN: "ACCOUNT_PAUSES_SCREEN",
  ACCOUNT_ADD_PAUSE_SCREEN: "ACCOUNT_ADD_PAUSE_SCREEN",
  ACCOUNT_BUDGETS_SCREEN: "ACCOUNT_BUDGETS_SCREEN",

  // -- PROFILE_STACK
  PROFILE_SCREEN: "PROFILE_SCREEN",
  EDIT_CONTACT_INFORMATION_SCREEN: "EDIT_CONTACT_INFORMATION_SCREEN",
};
