export const Stacks = {
  AUTH_STACK: "AUTH_STACK",
  MAIN_STACK: "MAIN_STACK",
  /* - */ ACCOUNT_STACK: "ACCOUNT_STACK",
  /* - */ PROFILE_STACK: "PROFILE_STACK",
  /* - */ HOME_STACK: "HOME_STACK", //BottomTabNavigator
  /* -- */ SUMMERY_STACK: "SUMMARY_STACK",
  /* -- */ CAMPAIGN_STACK: "CAMPAIGN_STACK",
  /* -- */ BILLING_STACK: "BILLING_STACK",
};
